import { banner1, banner2, banner3 } from "../assets/Cards";
import {
  product_1_1,
  product_1_2,
  product_2_1,
  product_2_2,
  product_3_1,
  product_3_2,
  product_4_1,
  product_4_2,
  product_5_1,
  product_5_2,
  product_6_1,
  product_6_2,
  product_7_1,
  product_7_2,
  product_8_1,
  product_8_2,
  product_9_1,
  product_9_2,
  product_10_1,
  product_10_2,
} from "../assets/Products";
import {
    thumbnail_1,
    thumbnail_2,
    thumbnail_3,
    thumbnail_4,
    thumbnail_5,
    thumbnail_6,
    thumbnail_7,
    thumbnail_8,
    thumbnail_9,
    thumbnail_10,
    thumbnail_11,
    thumbnail_12,
  } from "../assets/Fruit & vegetables/index";
import { icon1, icon2, icon3, icon4, icon5 } from "../assets/FooterIcons";
import {
  cat1,
  cat2,
  cat3,
  cat4,
  cat5,
  cat9,
  cat11,
  cat12,
  cat13,
  cat14,
} from "../assets/Categories";
import {
    icon_1,
    icon_2,
    icon_3,
    icon_4,
    icon_5,
    icon_6,
  } from "../../assets/About";

export let BannerDetails = [
  { title: "Everyday Fresh and clean with our Products", img: banner1 },
  { title: "Make your Breakfast Healthy and Easy", img: banner2 },
  { title: "The best Organic Products Online", img: banner3 },
];

export let BestSellsProduct = [
  {
    sale: "Hot",
    saleBg: "#f59758",
    img: product_1_1,
    hovImg: product_1_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
  {
    sale: "sale",
    saleBg: "#3bb77e",
    img: product_2_1,
    hovImg: product_2_2,
    type: "Hodo Foods",
    heading: "All Natural Italian-Style Chicken Meatballs & Red Rice",
    seller: "Stouffer",
    price: 52.85,
    discount: 55.8,
  },
  {
    sale: "New",
    saleBg: "#f74b81",
    img: product_3_1,
    hovImg: product_3_2,
    type: "snack",
    heading: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
    seller: "StarKist",
    price: 48.85,
    discount: 52.8,
  },
  {
    sale: "Hot",
    saleBg: "#ac3ef5",
    img: product_4_1,
    hovImg: product_4_2,
    type: "Vegetables",
    heading: "Foster Farms Takeout Crispy Classic Buffalo Wings",
    seller: "NestFood",
    price: 17.85,
    discount: 19.8,
  },
  {
    sale: "Hot",
    saleBg: "#f59758",
    img: product_5_1,
    hovImg: product_5_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
  {
    sale: "Hot",
    saleBg: "#f74b81",
    img: product_6_1,
    hovImg: product_6_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
  {
    sale: "Hot",
    saleBg: "#3bb77e",
    img: product_7_1,
    hovImg: product_7_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
  {
    sale: "Hot",
    saleBg: "#f74b81",
    img: product_8_1,
    hovImg: product_8_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
  {
    sale: "Hot",
    saleBg: "#3bb77e",
    img: product_9_1,
    hovImg: product_9_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
  {
    sale: "Hot",
    saleBg: "#f59758",
    img: product_10_1,
    hovImg: product_10_2,
    type: "snack",
    heading: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    seller: "NestFood",
    price: 28.85,
    discount: 32.8,
  },
];

export let CategoryList = [
  { Name: "Peach", img: cat1, items: 14, bgColor: "#f2fce4" },
  { Name: "Cake and Milk", img: cat2, items: 14, bgColor: "#fff3eb" },
  { Name: "organic kiwi", img: cat3, items: 14, bgColor: "#f3e8e8" },
  { Name: "Vegetables", img: cat4, items: 14, bgColor: "#f2fce4" },
  { Name: "Strawberry", img: cat5, items: 14, bgColor: "#fff3eb" },
  { Name: "Black Plum", img: cat9, items: 14, bgColor: "#f3e8e8" },
  { Name: "Custard apple", img: cat11, items: 14, bgColor: "#f2fce4" },
  { Name: "Peach", img: cat12, items: 14, bgColor: "#fff3eb" },
  { Name: "Peach", img: cat13, items: 14, bgColor: "#f2fce4" },
  { Name: "Peach", img: cat14, items: 14, bgColor: "#fff3eb" },
];

export let QuickViewList = [
  {
    img: icon1,
    heading: "Best prices & offers",
    subHeading: "Orders $50 or more",
  },
  {
    img: icon2,
    heading: "Free delivery",
    subHeading: "24/7 amazing services",
  },
  {
    img: icon3,
    heading: "Great daily deal",
    subHeading: "When you sign up",
  },
  {
    img: icon4,
    heading: "Wide assortment",
    subHeading: "Mega Discounts",
  },
  {
    img: icon5,
    heading: "Easy returns",
    subHeading: "Within 30 days",
  },
];
export let FruitArray = [
    {
      img: thumbnail_1,
      heading: "Nestle Original Coffee-Mate Coffee Creamer",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_2,
      heading: "Nestle Original Coffee-Mate Coffee Creamer",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_3,
      heading: "Nestle Original Coffee-Mate Coffee Creamer",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_4,
      heading: "Organic Cage-Free Grade A Large Brown Eggs",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_5,
      heading: "Organic Frozen Triple Berry Blend",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_6,
      heading: "Organic Frozen Triple Berry Blend",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_7,
      heading: "Nestle Original Coffee-Mate Coffee Creamer",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_8,
      heading: "Organic Frozen Triple Berry Blend",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_9,
      heading: "Nestle Original Coffee-Mate Coffee Creamer",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_10,
      heading: "Organic Frozen Triple Berry Blend",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_11,
      heading: "Organic Frozen Triple Berry Blend",
      price: 32.85,
      discount: 33.8,
    },
    {
      img: thumbnail_12,
      heading: "Nestle Original Coffee-Mate Coffee Creamer",
      price: 32.85,
      discount: 33.8,
    },
  ];
  export let serviceData = [
    {
      img: icon_1,
      heading: "Best Prices & Offers",
      desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form",
    },
    {
      img: icon_2,
      heading: "Wide Assortment",
      desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form",
    },
    {
      img: icon_3,
      heading: "Free Delivery",
      desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form",
    },
    {
      img: icon_4,
      heading: "Easy Returns",
      desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form",
    },
    {
      img: icon_5,
      heading: "100% Satisfaction",
      desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form",
    },
    {
      img: icon_6,
      heading: "Great Daily Deal",
      desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form",
    },
  ];